In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/nlp/NATURAL LANGUAGE PROCESSING/UpdatedResumeDataSet.csv')

In [ ]:
data.head()

Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills • R • Python • SAP HANA • Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [ ]:
data['Resume'][0]

'Skills * Programming Languages: Python (pandas, numpy, scipy, scikit-learn, matplotlib), Sql, Java, JavaScript/JQuery. * Machine learning: Regression, SVM, Naïve Bayes, KNN, Random Forest, Decision Trees, Boosting techniques, Cluster Analysis, Word Embedding, Sentiment Analysis, Natural Language processing, Dimensionality reduction, Topic Modelling (LDA, NMF), PCA & Neural Nets. * Database Visualizations: Mysql, SqlServer, Cassandra, Hbase, ElasticSearch D3.js, DC.js, Plotly, kibana, matplotlib, ggplot, Tableau. * Others: Regular Expression, HTML, CSS, Angular 6, Logstash, Kafka, Python Flask, Git, Docker, computer vision - Open CV and understanding of Deep learning.Education Details \r\n\r\nData Science Assurance Associate \r\n\r\nData Science Assurance Associate - Ernst & Young LLP\r\nSkill Details \r\nJAVASCRIPT- Exprience - 24 months\r\njQuery- Exprience - 24 months\r\nPython- Exprience - 24 monthsCompany Details \r\ncompany - Ernst & Young LLP\r\ndescription - Fraud Investigatio

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
import re
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
corpus = []
for i in range(0, len(data['Resume'])):
    review = re.sub('[^a-zA-Z]', ' ', data['Resume'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

# bag of words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2000)
x = cv.fit_transform(corpus).toarray()
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
data['Category'].value_counts().index

Index(['Java Developer', 'Testing', 'DevOps Engineer', 'Python Developer',
       'Web Designing', 'HR', 'Hadoop', 'Operations Manager', 'Sales',
       'Data Science', 'ETL Developer', 'Blockchain', 'Mechanical Engineer',
       'Arts', 'Database', 'Electrical Engineering', 'Health and fitness',
       'PMO', 'DotNet Developer', 'Business Analyst', 'Automation Testing',
       'Network Security Engineer', 'Civil Engineer', 'SAP Developer',
       'Advocate'],
      dtype='object')

In [ ]:
y = data['Category']

In [ ]:

from sklearn import preprocessing

# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
y = label_encoder.fit_transform(data['Category'])

In [ ]:
#OneHotEncoder = preprocessing.OneHotEncoder()
#y = OneHotEncoder.fit_transform(y)

In [ ]:
y

array([ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 22

In [ ]:
import numpy as np
data['Category'].values

array(['Data Science', 'Data Science', 'Data Science', 'Data Science',
       'Data Science', 'Data Science', 'Data Science', 'Data Science',
       'Data Science', 'Data Science', 'Data Science', 'Data Science',
       'Data Science', 'Data Science', 'Data Science', 'Data Science',
       'Data Science', 'Data Science', 'Data Science', 'Data Science',
       'Data Science', 'Data Science', 'Data Science', 'Data Science',
       'Data Science', 'Data Science', 'Data Science', 'Data Science',
       'Data Science', 'Data Science', 'Data Science', 'Data Science',
       'Data Science', 'Data Science', 'Data Science', 'Data Science',
       'Data Science', 'Data Science', 'Data Science', 'Data Science',
       'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR',
       'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR',
       'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR',
       'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR', 'HR'

In [ ]:
from collections import Counter
Counter(data['Category'].values)

Counter({'Advocate': 20,
         'Arts': 36,
         'Automation Testing': 26,
         'Blockchain': 40,
         'Business Analyst': 28,
         'Civil Engineer': 24,
         'Data Science': 40,
         'Database': 33,
         'DevOps Engineer': 55,
         'DotNet Developer': 28,
         'ETL Developer': 40,
         'Electrical Engineering': 30,
         'HR': 44,
         'Hadoop': 42,
         'Health and fitness': 30,
         'Java Developer': 84,
         'Mechanical Engineer': 40,
         'Network Security Engineer': 25,
         'Operations Manager': 40,
         'PMO': 30,
         'Python Developer': 48,
         'SAP Developer': 24,
         'Sales': 40,
         'Testing': 70,
         'Web Designing': 45})

In [ ]:
y = pd.DataFrame(y)

In [ ]:
index_cat = pd.DataFrame(data['Category'].value_counts())
index_num = pd.DataFrame(y[0].value_counts())

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, random_state = 0, test_size = 0.3)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(673, 2000)
(289, 2000)
(673, 1)
(289, 1)


In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(random_state=0, multi_class='ovr')

In [ ]:
model = model.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_predict = model.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_predict,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         4
           2       1.00      0.89      0.94         9
           3       1.00      0.94      0.97        16
           4       1.00      1.00      1.00        10
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00        14
           7       1.00      1.00      1.00        10
           8       0.87      1.00      0.93        13
           9       1.00      1.00      1.00        10
          10       1.00      1.00      1.00        11
          11       1.00      1.00      1.00        13
          12       1.00      1.00      1.00        12
          13       1.00      1.00      1.00        13
          14       1.00      1.00      1.00         9
          15       1.00      1.00      1.00        26
          16       1.00      1.00      1.00         9
          17       1.00    

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_predict,y_test)

0.9930795847750865

In [ ]:
keys = np.unique(data['Category'].values)

In [ ]:
val  = np.unique(y)

In [ ]:
dict(zip(keys, val))

{'Advocate': 0,
 'Arts': 1,
 'Automation Testing': 2,
 'Blockchain': 3,
 'Business Analyst': 4,
 'Civil Engineer': 5,
 'Data Science': 6,
 'Database': 7,
 'DevOps Engineer': 8,
 'DotNet Developer': 9,
 'ETL Developer': 10,
 'Electrical Engineering': 11,
 'HR': 12,
 'Hadoop': 13,
 'Health and fitness': 14,
 'Java Developer': 15,
 'Mechanical Engineer': 16,
 'Network Security Engineer': 17,
 'Operations Manager': 18,
 'PMO': 19,
 'Python Developer': 20,
 'SAP Developer': 21,
 'Sales': 22,
 'Testing': 23,
 'Web Designing': 24}

In [ ]:
d = {'Advocate': 0, 'Arts': 1, 'Automation Testing': 2 , 'Blockchain': 3,
       'Business Analyst': 4, 'Civil Engineer': 5, 'Data Science': 6, 'Database': 7,
       'DevOps Engineer': 8, 'DotNet Developer': 9, 'ETL Developer': 10,
       'Electrical Engineering': 11, 'HR': 12, 'Hadoop': 13 , 'Health and fitness': 14,
       'Java Developer': 15, 'Mechanical Engineer': 16,
       'Network Security Engineer': 17, 'Operations Manager': 18, 'PMO': 19,
       'Python Developer': 20, 'SAP Developer': 21, 'Sales': 22, 'Testing': 23,
       'Web Designing': 24}

In [ ]:
def pred(corpus):
    msg = cv.transform([corpus])
    prediction = model.predict(msg)
    return prediction[0]

In [ ]:
val = pred(data['Resume'][45])

In [ ]:
for k,v in d.items():
  if v == val:
    print(k)

HR


In [ ]:
index_cat = pd.DataFrame(data['Category'].value_counts())
index_num = pd.DataFrame(y[0].value_counts())

In [ ]:
index_num.reset_index(level = 0, inplace= True)

In [ ]:
index_cat.reset_index(level = 0, inplace= True)

In [ ]:
a = index_num['index'].values

In [ ]:
b = index_cat['index'].values

In [ ]:
print(len(a))
print(len(b))

25
25


In [ ]:
a

array([15, 23,  8, 20, 24, 12, 13, 18, 16, 10,  3, 22,  6,  1,  7, 19, 14,
       11,  4,  9,  2, 17,  5, 21,  0])

In [ ]:
b

array(['Java Developer', 'Testing', 'DevOps Engineer', 'Python Developer',
       'Web Designing', 'HR', 'Hadoop', 'Blockchain', 'Sales',
       'Data Science', 'ETL Developer', 'Operations Manager',
       'Mechanical Engineer', 'Arts', 'Database', 'Health and fitness',
       'PMO', 'Electrical Engineering', 'DotNet Developer',
       'Business Analyst', 'Automation Testing',
       'Network Security Engineer', 'SAP Developer', 'Civil Engineer',
       'Advocate'], dtype=object)

In [ ]:
d = {15:'Java Developer', 23:'Testing',  8:'DevOps Engineer', 20:'Python Developer', 
     24 : 'Web Designing', 12: 'HR', 13 :'Hadoop', 18 : 'Blockchain', 16 : 'Sales',
     10: 'Data Science',  3:'ETL Developer', 22:'Operations Manager',  
     6:,  1:,  7, 19, 14,
       11,  4,  9,  2, 17,  5, 21,  0]}

In [ ]:
data['Category'][45]

'HR'